name:   'FuturisticSEC Blog'
url:    'www.futuristicsec.com'
author: 'Umoru L. Zakari'
description: 'Digital Security Products and Services.'
avatar: '/img/avatar.png'
email: 'zak@futuristicsec.com'
disqus: 'futuristicsec'
google_analytics: 'UA-72237868-1' 
 
gems:  [jekyll-paginate]

include:  ['_pages']

paginate:      10
paginate_path: '/blog/page:num/'
permalink:     '/blog/:year/:title/'


excerpt_separator: "{{ more }}"


markdown: kramdown
timezone: Africa/Lagos
highlighter:  rouge

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
