name:   'FuturisticSEC Website and Blog'
url:    'www.futuristicsec.com'
author: 'Umoru Lucky Zakari'

include:  ['_pages']

paginate:      10
paginate_path: '/blog/page:num/'
permalink:     '/blog/:year/:title/'
relative_permalinks: false

excerpt_separator: "{{ more }}"

safe:     true
markdown: 'kramdown'
timezone: 'Africa/Lagos'
highlighter: 'pygments'
